version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata3:/var/lib/postgresql/data
      - ./sql/prompts.sql:/docker-entrypoint-initdb.d/prompts.sql

volumes:
  pgdata3:
    driver: local
